services:
  # Backend API Service
  - type: web
    name: pancakes-backend
    runtime: node
    buildCommand: cd backend && npm install
    startCommand: cd backend && node server.js
    healthCheckPath: /api/health
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: pancakes-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: PORT
        value: 10000
      - key: FRONTEND_URL
        value: https://pancakes-frontend.onrender.com

  # Frontend Static Site
  - type: web
    name: pancakes-frontend
    runtime: static
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: ./frontend/build
    plan: free
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: REACT_APP_API_URL
        value: https://pancakes-backend.onrender.com

# PostgreSQL Database
databases:
  - name: pancakes-db
    databaseName: pancakes_analytics
    user: pancakes_user
    plan: free